# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'BDC-11-L-6R8YTT2'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test package'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\Program Files\Java\jdk1.8.0_211'
    mavenVersionOption: 'Path'
    mavenDirectory: 'C:\Users\manoj.reddy.kusam\Downloads\apache-maven-3.6.1'
    mavenSetM2Home: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    
    
        
   

