- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'Path'
    jdkDirectory: 'C:\Program Files\Java\jdk1.8.0_211'
    mavenVersionOption: 'Path'
    mavenDirectory: 'C:\Users\manoj.reddy.kusam\Downloads\apache-maven-3.6.1'
    mavenSetM2Home: true
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    